export const SIGN_IN_WITH_GOOGLE_POPUP = 'SIGN_IN_WITH_GOOGLE_POPUP'
export const SIGN_OUT = 'SIGN_OUT'
export const SET_LOADING = 'SET_LOADING'
export const SET_USER = 'SET_USER'
export const SET_ERROR = 'SET_ERROR'
